# Generated by Django 5.1.4 on 2025-01-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_remove_subscription_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
